Array Transposition

In [1]:
import numpy as np

In [2]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr=np.random.randn(6,3)
arr

array([[ 0.29095259, -1.01737863, -1.55246572],
       [ 0.14714112, -0.85949033,  0.25525838],
       [-0.02601747, -0.23249494, -0.37853186],
       [-2.105415  , -0.76321969,  1.33386092],
       [-1.01490375, -0.18136088, -1.41663058],
       [-0.38580054, -0.3267195 , -0.06822701]])

In [5]:
np.dot(arr.T, arr)

array([[ 5.71862484,  1.5005802 , -1.74855155],
       [ 1.5005802 ,  2.5499785 ,  0.70924362],
       [-1.74855155,  0.70924362,  6.4092751 ]])

In [6]:
arr=np.arange(16).reshape(2,2,4)

In [7]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])